name: drone-test
kind: pipeline
type: docker

steps:
- name: test
  image: docker/compose
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - whoami
  - docker-compose up -d
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
