name: drone-test
type: docker
kind: pipeline
steps:
- name: test
  image: compose:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - up
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
